post_id: 2025-12-25T20-07-41-restrictive-agents-are-cheaper-and-thats-not-an-accident
title: "Restrictive Agents Are Cheaper (and That\u2019s Not an Accident)"
author: Andreas Atle
created_at: 2025-12-25 20:07:41+00:00
status: published
