post_id: 2025-12-27T13-44-17-becoming-the-supervisor-how-building-an-agentic-framework-changed-how-i-develop-software
title: 'Becoming the Supervisor: How Building an Agentic Framework Changed How I Develop
  Software'
author: Andreas Atle
created_at: 2025-12-27 13:44:17+00:00
status: published
